{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "NameError: name 'Path' is not defined", "trace": "def test_create_auth_with_excel():\n>       file_path = Path(__file__).parent / \"testdata_ddt.xlsx\"\nE       NameError: name 'Path' is not defined\n\ntests\\test\\datadriventesting\\test_ddt_for.py:48: NameError"}, "start": 1735531064568, "stop": 1735531064568, "uuid": "f3a20ab9-2af9-4592-9bff-0edaecb887e2", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "35976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}