{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "KeyError: 'token'", "trace": "def test_create_auth_with_excel():\n        file_path = \"C:/Users/mutay/OneDrive/Documents/courses/PyATB/code files/pyProject1-AutomationFramework/tests/test/datadriventesting/testdata_ddt.xlsx\"\n        credentials = read_credentials_from_excel(file_path)\n    \n        for user in credentials:\n            username = user[\"username\"]\n            password = user[\"password\"]\n    \n            # Create the auth request and get the response\n            response = create_auth_request(username=username, password=password)\n    \n            # Log and assert response status and token presence\n            logger.info(f\"Testing with username: {username}\")\n            assert response.status_code == 200, f\"Expected status code 200, but got {response.status_code}\"\n            #assert response.headers[\"Content-Type\"] == \"application/json\", \"Response is not in JSON format\"\n            response_json = response.json()\n            if type(response_json) == dict:\n                pass\n            else:\n                assert response_json.get(\"token\") is not None, \"Token is missing in the response\"\n    \n>           token=response_json[\"token\"]\nE           KeyError: 'token'\n\ntests\\test\\datadriventesting\\test_ddt_for.py:74: KeyError"}, "start": 1735566777861, "stop": 1735566778962, "uuid": "a1515c06-d6bb-418f-941e-c289e3a8a18f", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "37092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}