{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm", "trace": "def test_create_auth_with_excel():\n        file_path = Path(__file__).parent / \"testdata_ddt.xlsx\"\n        file_path=\"\\tests\\test\\datadriventesting\"\n>       credentials=read_credentials_from_excel(file_path)\n\ntests\\test\\datadriventesting\\test_ddt_for.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests\\test\\datadriventesting\\test_ddt_for.py:15: in read_credentials_from_excel\n    workbook=openpyxl.load_workbook(filename=filepath)\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:346: in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:123: in __init__\n    self.archive = _validate_archive(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilename = '\\tests\\test\\\\datadriventesting'\n\n    def _validate_archive(filename):\n        \"\"\"\n        Does a first check whether filename is a string or a file-like\n        object. If it is a string representing a filename, a check is done\n        for supported formats by checking the given file-extension. If the\n        file-extension is not in SUPPORTED_FORMATS an InvalidFileException\n        will raised. Otherwise the filename (resp. file-like object) will\n        forwarded to zipfile.ZipFile returning a ZipFile-Instance.\n        \"\"\"\n        is_file_like = hasattr(filename, 'read')\n        if not is_file_like:\n            file_format = os.path.splitext(filename)[-1].lower()\n            if file_format not in SUPPORTED_FORMATS:\n                if file_format == '.xls':\n                    msg = ('openpyxl does not support the old .xls file format, '\n                           'please use xlrd to read this file, or convert it to '\n                           'the more recent .xlsx file format.')\n                elif file_format == '.xlsb':\n                    msg = ('openpyxl does not support binary format .xlsb, '\n                           'please convert this file to .xlsx format if you want '\n                           'to open it with openpyxl')\n                else:\n                    msg = ('openpyxl does not support %s file format, '\n                           'please check you can open '\n                           'it with Excel first. '\n                           'Supported formats are: %s') % (file_format,\n                                                           ','.join(SUPPORTED_FORMATS))\n>               raise InvalidFileException(msg)\nE               openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm\n\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:93: InvalidFileException"}, "start": 1735554547993, "stop": 1735554547994, "uuid": "881d796b-64fa-4c49-8a05-56bf2ddc2f64", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "38356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}